### ISSUE TITLE
Cellular HTML5: cannot change costume size

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#52]
Cellular HTML5: 

I cannot figure out how to change costume size. Right-clicking the costume did not give me the option, and the resizing options in the paint window are gone.

![cannot_change_sprite_size](https://cloud.githubusercontent.com/assets/714256/7647280/bcc6025e-fa86-11e4-88d0-318f58c89f3d.png)

**Comment by Craxic** [comment]
Hi Mark.

This is the default behaviour of "Snap!", so cellular will also lack such a feature. However, new "grow" and "shrink" buttons have been added since #54 was fixed. Perhaps they might be what you want? Also consider using:

![download](https://cloud.githubusercontent.com/assets/4537985/7665157/5d08c86a-fbee-11e4-9090-d2bbb82f4132.png)

Let me know if there's anything else I can do. Other than that, since the canvas is already as large as the stage I'm not sure why anybody would really need it much larger.

**Comment by mciotola** [comment]
Hi Matt,

Thanks for letting me know about this history of this.  I am resizing
costumes outside of Cellular to reduce confusion, but I will try out the
block. Grow and shrink buttons would be great!

**Comment by Craxic** [comment]
Hi Mark.

Just try the latest version of cellular and you should get the new "Grow" and "Shrink" buttons.

I'll close this issue for now. Let me know if you have more questions.
