### ISSUE TITLE
Cellular HTML5: block parameter mismatch

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#78]
Cellular HTML5: 

Aidan pointed out that a neighbor (e.g. "objects in nbr cell" block should not be allowed to go into the parameter arrow of a an object block (e.g. "costume name of >"), that this results in a types mismatch. I think the issue is that one produces a list, but the other is not expecting a list, so the combination will not work.
![cellular_html5_object_in_arrow](https://cloud.githubusercontent.com/assets/714256/7804760/3566900a-031c-11e5-8f26-1b7af34b92bc.png)

**Comment by Craxic** [comment]
Hey guys. Since the base project ("Snap!") does not bother with preventing this, I'm not going to go all the way and prevent the user from doing this myself. 

For example, this should be impossible to set up, but "Snap!" is happy with it:
![screenshot from 2015-06-09 19 48 59](https://cloud.githubusercontent.com/assets/4537985/8055130/afb9067e-0ee0-11e5-8e72-49d56f2a5d8f.png)

Closing, let me know if that's OK.

**Comment by aidanlane** [comment]
Fair enough...
@mciotola, do you think that it's worth creating an issue on https://github.com/jmoenig/Snap--Build-Your-Own-Blocks ?

**Comment by mciotola** [comment]
I can't tell whether this issue will cause us problems until we delve into
the Neighbor blocks issue.
